version: '3.8'

services:
  meditation-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:3001"
    environment:
      - PORT=3001
      - NODE_ENV=production
      # API keys from host environment
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
    volumes:
      # Mount the data directory for persistence
      - meditation-data:/app/data

volumes:
  meditation-data:
    # Use named volume for data persistence between container restarts
    driver: local