version: '3.8'

services:
  meditation-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:3001"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      # Map data directory to host filesystem
      - ./backend/data:/app/data
      # Map audio cache directory specifically
      - ./backend/data/audio-cache:/app/data/audio-cache
      # Map presets directory
      - ./backend/data/presets:/app/data/presets