version: '3.8'

services:
  meditation-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:3001"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      # Mount the data directory for persistence
      - meditation-data:/app/data

volumes:
  meditation-data:
    # Use named volume for data persistence between container restarts
    driver: local