version: '3.8'

services:
  contemplation-machine:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # Default external port 8088 when not specified in .env or environment
      # Internal port fixed at 3001
      - "${PORT:-8088}:3001"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      # Force the internal port to be fixed at 3001 regardless of .env settings
      - PORT=3001
    volumes:
      # Mount .env file so changes are reflected without rebuilding
      - ./.env:/app/.env
      # Map data directory to host filesystem
      - ./backend/data:/app/data
      # We're removing the specific audio-cache mapping to allow the initialization code to work
      # Map presets directory
      - ./backend/data/presets:/app/data/presets
      # Remove mappings for defaults directories as they should come from the container image