version: '3.8'

services:
  contemplation-machine:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:3001"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      # Map data directory to host filesystem
      - ./backend/data:/app/data
      # We're removing the specific audio-cache mapping to allow the initialization code to work
      # Map presets directory
      - ./backend/data/presets:/app/data/presets
      # Remove mappings for defaults directories as they should come from the container image